//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace algo1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("algo1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6
        ///0 0.25 0.33
        ///1 0.73 0.47
        ///2 1.00 0.54
        ///3 0.34 0.60
        ///4 0.81 0.20
        ///5 1.07 0.28
        ///7
        ///0 1 0.50 20
        ///0 3 0.28 80
        ///3 4 0.62 80
        ///1 4 0.28 40
        ///1 2 0.28 40
        ///4 5 0.27 60
        ///2 5 0.27 60.
        /// </summary>
        internal static string map1 {
            get {
                return ResourceManager.GetString("map1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6
        ///0 0.25 0.33
        ///1 0.73 0.47
        ///2 1.00 0.54
        ///3 0.34 0.60
        ///4 0.81 0.20
        ///5 1.07 0.28
        ///7
        ///0 1 0.50 20
        ///0 3 0.28 30
        ///3 4 0.62 20
        ///1 4 0.28 40
        ///1 2 0.28 20
        ///4 5 0.27 30
        ///2 5 0.27 10.
        /// </summary>
        internal static string map2 {
            get {
                return ResourceManager.GetString("map2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9
        ///0 6.58 4.65
        ///1 22.8 4.63
        ///2 39.6 4.63
        ///3 39.5 19.05
        ///4 22.67 20.19
        ///5 5.89 20.87
        ///6 4.75 36.51
        ///7 22.55 36.29
        ///8 39.56 36.63
        ///12
        ///0 1 16 80
        ///1 2 16 100
        ///2 3 16 80
        ///3 8 16 100
        ///8 7 16 80
        ///6 7 16 80
        ///6 5 16 10
        ///0 5 16 20
        ///4 5 16 20
        ///4 1 16 10
        ///4 7 16 20
        ///4 3 16 10.
        /// </summary>
        internal static string map3 {
            get {
                return ResourceManager.GetString("map3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9
        ///0 6.58 4.65
        ///1 22.8 4.63
        ///2 39.6 4.63
        ///3 39.5 19.05
        ///4 22.67 20.19
        ///5 5.89 20.87
        ///6 4.75 36.51
        ///7 22.55 36.29
        ///8 39.56 36.63
        ///8
        ///0 1 16 80
        ///1 2 16 100
        ///2 3 16 80
        ///8 7 16 80
        ///6 7 16 80
        ///6 5 16 10
        ///4 5 16 20
        ///4 3 16 10.
        /// </summary>
        internal static string map4 {
            get {
                return ResourceManager.GetString("map4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9
        ///0 6.58 4.65
        ///1 22.8 4.63
        ///2 39.6 4.63
        ///3 39.5 19.05
        ///4 22.67 20.19
        ///5 5.89 20.87
        ///6 4.75 36.51
        ///7 22.55 36.29
        ///8 39.56 36.63
        ///8
        ///0 1 16 80
        ///1 2 16 100
        ///8 7 16 80
        ///6 7 16 80
        ///4 5 16 20
        ///4 1 16 10
        ///4 7 16 20
        ///4 3 16 10.
        /// </summary>
        internal static string map5 {
            get {
                return ResourceManager.GetString("map5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6105
        ///0 769.949 2982.98
        ///1 863.276 3005.28
        ///2 690.196 3333.7
        ///3 1197.56 2984.47
        ///4 1261.19 2985.96
        ///5 722.437 3467.45
        ///6 1316.34 2999.33
        ///7 749.586 3781.02
        ///8 1474.14 2737.78
        ///9 1662.92 3148.68
        ///10 1771.94 2439.07
        ///11 842.914 4259.55
        ///12 1794.85 2392.26
        ///13 1830.06 2468.05
        ///14 1807.15 2400.43
        ///15 1834.3 2414.92
        ///16 1827.94 2339.13
        ///17 1871.21 2504.46
        ///18 1836.42 2342.47
        ///19 1863.15 2431.27
        ///20 1834.3 2304.58
        ///21 2090.95 3406.9
        ///22 1885.63 2449.47
        ///23 1877.57 2359.19
        ///24 1910.66 2540.5
        ///25 1845.33 2276.34
        ///2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OLMap {
            get {
                return ResourceManager.GetString("OLMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2183 2174 2171 2167 2178 2221 2186 2166 2196 2204 2229 4317 4300 4292 4281 4285 4288 4295 672 650 640 624 623 606 601 597 595 593 631 710 711 712 714 731 803 831 829 830 833 947 948 949 951 977 982 1044 1876 1886 1836 1814 1809 1832 1833 1816 1818 1869 1895 1973 1970 1961 1953 1975 4575 4572 4571 4562 4552 4550 4564 4567
        ///6017.82 mins
        ///10388.73 km
        ///31.98 km
        ///10356.76 km
        ///
        ///3478 3476 3474 3472 3462 3456 3454 3452 227 194 162 159 139 134 128 126 129 184 236 237 238 239 270 309 592 593 631 710 711 712 714 720  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OLOutput {
            get {
                return ResourceManager.GetString("OLOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1000
        ///4427.32 1330.61 5440.53 8567.77 26432
        ///7672.66 3261.51 2547.07 4849.7 24638
        ///5963.01 8559.53 3340.56 5829.95 30232
        ///4980.93 9187.29 4256.11 2153.39 18510
        ///5094.45 4599.75 5467.7 2049.62 25329
        ///3158.67 1399.58 1611.07 5424.97 25823
        ///4660.48 6818.45 5426.19 4235.05 30407
        ///1467.64 5096.9 2023.68 2540.36 25808
        ///3094.88 7083.04 8377.33 2801.6 17570
        ///5941.04 8040.41 6259.04 9179.97 30480
        ///5995.97 5908.99 3786.13 7495.35 28753
        ///1601 6036.87 5433.21 7878.35 24264
        ///1739.25 5818.66 3682.97 5793.94 30525
        ///5646.8 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OLQueries {
            get {
                return ResourceManager.GetString("OLQueries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 3 4 5 2
        ///4.63 mins
        ///1.72 km
        ///0.28 km
        ///1.44 km
        ///
        ///0 ms
        ///
        ///7 ms
        ///.
        /// </summary>
        internal static string output1 {
            get {
                return ResourceManager.GetString("output1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 1 0
        ///4.06 mins
        ///0.92 km
        ///0.14 km
        ///0.78 km
        ///
        ///3 4
        ///5.04 mins
        ///0.89 km
        ///0.27 km
        ///0.62 km
        ///
        ///0 1 4
        ///4.43 mins
        ///0.99 km
        ///0.21 km
        ///0.78 km
        ///
        ///4 1
        ///1.90 mins
        ///0.40 km
        ///0.12 km
        ///0.28 km
        ///
        ///0 1 4 5
        ///4.61 mins
        ///1.23 km
        ///0.18 km
        ///1.05 km
        ///
        ///3 0 1 2
        ///5.09 mins
        ///1.24 km
        ///0.18 km
        ///1.06 km
        ///
        ///4 1 0
        ///5.18 mins
        ///1.05 km
        ///0.27 km
        ///0.78 km
        ///
        ///3 4
        ///4.08 mins
        ///0.80 km
        ///0.18 km
        ///0.62 km
        ///
        ///4 1 0
        ///4.58 mins
        ///1.00 km
        ///0.22 km
        ///0.78 km
        ///
        ///2 1 0
        ///5.23 mins
        ///1.02 km
        ///0.24 km
        ///0.78 km
        ///
        ///0 ms
        ///
        ///2 ms
        ///.
        /// </summary>
        internal static string output2 {
            get {
                return ResourceManager.GetString("output2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 4
        ///222.32 mins
        ///30.53 km
        ///14.53 km
        ///16.00 km
        ///
        ///6 7 8 3 2 1
        ///232.05 mins
        ///94.74 km
        ///14.74 km
        ///80.00 km
        ///
        ///7 8 3 2 1
        ///182.64 mins
        ///75.62 km
        ///11.62 km
        ///64.00 km
        ///
        ///6 7 8 3 2 1 0
        ///168.93 mins
        ///104.48 km
        ///8.48 km
        ///96.00 km
        ///
        ///0 1 2 3
        ///223.70 mins
        ///63.84 km
        ///15.84 km
        ///48.00 km
        ///
        ///1 0 5
        ///159.28 mins
        ///40.27 km
        ///8.27 km
        ///32.00 km
        ///
        ///1 2 3 8 7 6
        ///202.42 mins
        ///92.27 km
        ///12.27 km
        ///80.00 km
        ///
        ///7 8 3
        ///114.91 mins
        ///39.78 km
        ///7.78 km
        ///32.00 km
        ///
        ///4 7 8 3
        ///286.55 mins
        ///66.08 km
        ///18.08 km
        ///48.00 km
        ///
        ///4 7 8 3 2
        ///166.90 mi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string output3 {
            get {
                return ResourceManager.GetString("output3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 5 4 3 2 1
        ///438.45 mins
        ///94.74 km
        ///14.74 km
        ///80.00 km
        ///
        ///7 6 5 4
        ///325.73 mins
        ///62.14 km
        ///14.14 km
        ///48.00 km
        ///
        ///6 5 4 3 2 1 0
        ///375.33 mins
        ///104.48 km
        ///8.48 km
        ///96.00 km
        ///
        ///0 1 2 3
        ///223.70 mins
        ///63.84 km
        ///15.84 km
        ///48.00 km
        ///
        ///1 2 3 4 5
        ///264.88 mins
        ///72.27 km
        ///8.27 km
        ///64.00 km
        ///
        ///1 2 3 4 5 6
        ///408.82 mins
        ///92.27 km
        ///12.27 km
        ///80.00 km
        ///
        ///7 6 5 4 3
        ///345.31 mins
        ///71.78 km
        ///7.78 km
        ///64.00 km
        ///
        ///4 3
        ///312.95 mins
        ///34.08 km
        ///18.08 km
        ///16.00 km
        ///
        ///4 3 2
        ///193.30 mins
        ///39.11 km
        ///7.11 km
        ///32.00 km
        ///
        ///5 4
        ///166.97 mins        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string output4 {
            get {
                return ResourceManager.GetString("output4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7 4
        ///217.73 mins
        ///30.14 km
        ///14.14 km
        ///16.00 km
        ///
        ///6 7 4 1 0
        ///269.73 mins
        ///72.48 km
        ///8.48 km
        ///64.00 km
        ///
        ///0 1 2
        ///253.46 mins
        ///51.32 km
        ///19.32 km
        ///32.00 km
        ///
        ///1 4 5
        ///243.28 mins
        ///40.27 km
        ///8.27 km
        ///32.00 km
        ///
        ///1 4 7 6
        ///303.22 mins
        ///60.27 km
        ///12.27 km
        ///48.00 km
        ///
        ///7 4 3
        ///237.31 mins
        ///39.78 km
        ///7.78 km
        ///32.00 km
        ///
        ///4 7 8
        ///291.79 mins
        ///51.32 km
        ///19.32 km
        ///32.00 km
        ///
        ///4 1 2
        ///190.90 mins
        ///39.11 km
        ///7.11 km
        ///32.00 km
        ///
        ///5 4
        ///166.97 mins
        ///25.91 km
        ///9.91 km
        ///16.00 km
        ///
        ///5 4
        ///179.71 mins
        ///26.98 km
        ///10.98 km
        ///16.00 km        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string output5 {
            get {
                return ResourceManager.GetString("output5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1
        ///0.16 0.21 1.09 0.44 300.
        /// </summary>
        internal static string queries1 {
            get {
                return ResourceManager.GetString("queries1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10
        ///1.01197 0.480795 0.331957 0.343315 253
        ///0.389941 0.456355 0.911841 0.249623 241
        ///0.251276 0.419062 0.929659 0.204712 346
        ///0.846825 0.253127 0.727555 0.528648 132
        ///0.251451 0.28146 1.00373 0.392206 207
        ///0.436362 0.599414 1.02956 0.459127 218
        ///0.832962 0.324906 0.351052 0.226148 226
        ///0.313764 0.493588 0.73674 0.216578 137
        ///0.685588 0.209522 0.344595 0.310611 134
        ///0.95541 0.428584 0.251702 0.450459 261
        ///.
        /// </summary>
        internal static string queries2 {
            get {
                return ResourceManager.GetString("queries2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10
        ///7.3015 27.9344 21.7937 12.9203 7719
        ///10.3454 32.2451 30.448 5.53823 11003
        ///18.5573 35.1729 18.8263 10.9603 11261
        ///10.0317 32.331 7.83861 5.85562 10619
        ///7.49401 13.6 35.0139 13.8803 10375
        ///24.0857 4.89075 12.8512 20.8649 7780
        ///20.0324 8.15452 11.0676 31.957 8048
        ///22.8179 34.4698 37.0602 13.6381 6299
        ///15.4197 13.4496 39.1607 27.2225 11308
        ///25.5758 17.7779 39.4777 7.9592 4354
        ///.
        /// </summary>
        internal static string queries3 {
            get {
                return ResourceManager.GetString("queries3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10
        ///10.3454 32.2451 30.448 5.53823 11003
        ///18.5573 35.1729 18.8263 10.9603 11261
        ///10.0317 32.331 7.83861 5.85562 10619
        ///7.49401 13.6 35.0139 13.8803 10375
        ///24.0857 4.89075 12.8512 20.8649 7780
        ///20.0324 8.15452 11.0676 31.957 8048
        ///22.8179 34.4698 37.0602 13.6381 6299
        ///15.4197 13.4496 39.1607 27.2225 11308
        ///25.5758 17.7779 39.4777 7.9592 4354
        ///4.83615 20.6227 30.3778 24.5017 11873
        ///.
        /// </summary>
        internal static string queries4 {
            get {
                return ResourceManager.GetString("queries4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10
        ///18.5573 35.1729 18.8263 10.9603 11261
        ///10.0317 32.331 7.83861 5.85562 10619
        ///7.49401 13.6 35.0139 13.8803 10375
        ///24.0857 4.89075 12.8512 20.8649 7780
        ///20.0324 8.15452 11.0676 31.957 8048
        ///22.8179 34.4698 37.0602 13.6381 6299
        ///15.4197 13.4496 39.1607 27.2225 11308
        ///25.5758 17.7779 39.4777 7.9592 4354
        ///4.83615 20.6227 30.3778 24.5017 11873
        ///6.06351 23.3523 30.3512 16.5796 10076
        ///.
        /// </summary>
        internal static string queries5 {
            get {
                return ResourceManager.GetString("queries5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 174956
        ///0 1905.93 2760.6
        ///1 1910.9 2758.48
        ///2 1915.31 2764.82
        ///3 1915.86 2765.53
        ///4 1918.62 2754.26
        ///5 1878.36 2731.01
        ///6 1875.6 2728.19
        ///7 1870.64 2725.38
        ///8 1882.22 2727.49
        ///9 1943.99 2804.27
        ///10 1841.96 2715.51
        ///11 1798.39 2697.2
        ///12 1956.68 2698.61
        ///13 1792.87 2695.08
        ///14 1794.53 2692.97
        ///15 1914.21 2642.96
        ///16 1781.84 2697.9
        ///17 2012.38 2857.81
        ///18 1783.5 2700.72
        ///19 1776.88 2687.34
        ///20 1785.38 2704.95
        ///21 1781.41 2707.26
        ///22 1785.15 2683.11
        ///23 1909.24 2608.44
        ///24 2040.51 2874.72
        ///25 1755.37 2664.09
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SFMap {
            get {
                return ResourceManager.GetString("SFMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8311 8310 8312 8314 8315 154276 154272 154269 154262 154264 123573 123536 123498 123494 123493 123489 123490 123491 123492 123495 123496 123497 123499 123502 123503 123516 123551 123568 123582 132279 132278 132280 132282 132284 132287 132291 132288 132289 132293 132302 132315 132326 132330 132316 132351 132364 132380 159222 159224 159225 159226 159229 159231 159235 159238 159240 138611 138569 138563 138544 138534 138532 138541 138543 138570 138576 142074 142073 142059 142056 142047 142040 142009 142020 1420 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SFOutput {
            get {
                return ResourceManager.GetString("SFOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1000
        ///5188.56 7207.08 3129.77 4116.84 1996
        ///4304.83 5426.47 3386.22 4615.93 8107
        ///3309.62 4142.2 7518.06 4022.65 366
        ///5945.24 8331.93 4895.71 6218.81 3475
        ///1269.59 1937.2 6096.09 5399.92 8584
        ///4556.09 3404.1 4796.88 6286.97 4151
        ///4126.56 2933.89 4314.97 5788.12 1721
        ///6050.69 5296.1 3406.07 4683.69 370
        ///4622.65 6083.98 4535.34 5903.51 4826
        ///5331.96 7034.24 2914.69 4111.62 4875
        ///5270.47 6703.28 6579.47 5648.46 5901
        ///7222.62 4157.3 3851.14 2359.79 11
        ///5189.11 6844.71 4607.29 5926 5287
        ///3038.23 3885.57 5853.69  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SFQueries {
            get {
                return ResourceManager.GetString("SFQueries", resourceCulture);
            }
        }
    }
}
